---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: guanw0826/kubernetes-envoy-frontend:latest
        - name: envoy
          image: envoyproxy/envoy-dev:latest
          imagePullPolicy: Always
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.json"
            - "--mode serve"
            - "--service-cluster frontend"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
      volumes:
        - name: envoy
          configMap:
            name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-svc-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: frontend-svc
              servicePort: 8080
